# Renomme cette app avec ton propre nom (doit être unique sur fly.io)
app = "legifrance-proxy-darmon"
primary_region = "cdg"  # Paris

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
